# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:

- task: TerraformTaskV1@0
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'Internal Consumption tostille(7d5e75b2-656e-4a96-b12f-24e2e79a8279)'
    backendAzureRmResourceGroupName: 'ado-tf-function-demo'
    backendAzureRmStorageAccountName: 'tfstatetostille'
    backendAzureRmContainerName: 'state'
    backendAzureRmKey: 'terraform.tfstate'
    workingDirectory: '$(System.DefaultWorkingDirectory)/infra'
    
- task: TerraformTaskV1@0
  inputs:
    provider: 'azurerm'
    command: 'plan'
    commandOptions: '-out=tfplan.out'
    workingDirectory: '$(System.DefaultWorkingDirectory)/infra'
    environmentServiceNameAzureRM: 'Internal Consumption tostille(7d5e75b2-656e-4a96-b12f-24e2e79a8279)'
    
- task: TerraformTaskV1@0
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/infra'
    environmentServiceNameAzureRM: 'Internal Consumption tostille(7d5e75b2-656e-4a96-b12f-24e2e79a8279)'